require('dotenv').config();

const path = require('path');
const mongoose = require('mongoose');

const CLIENT_ID = process.env.CLIENT_ID;
const CLIENT_SECRET = process.env.CLIENT_SECRET;
const REDIRECT_URI = process.env.REDIRECT_URI || 'http://localhost:3000/auth/strava/callback';
const MONGO_URI = process.env.MONGO_URI;

// Connect to MongoDB
mongoose.connect(MONGO_URI, { useUnifiedTopology: true })
    .then(() => console.log('✅ Connected to MongoDB for update'))
    .catch(err => console.error('❌ Error connecting to MongoDB:', err));


// Define Schema for Athletes
const athleteSchema = new mongoose.Schema({
    athleteId: { type: String, required: true, unique: true },
    accessToken: { type: String, required: true },
    refreshToken: { type: String, required: true },
    firstname: { type: String },
    lastname: { type: String },
    profile: { type: String },
    gender: { type: String },
    restDay: { type: String, default: "Monday" },
    team: { type: String, default: "blue" },
    email: { type: String },
    source: { type: String, default: "strava" },
    category: { type: String, default: "100" }
});

const Athlete = mongoose.model('Athlete', athleteSchema);

const updates = async () => {
    const bulkOps = [
        { updateOne: { filter: { "email": "write.neetu@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "Vivekdbest2019@yahoo.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "rsharma1012@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "anie.misra@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "sonalchalana@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "nkaur07@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "rituchaudhary2585@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "negi.yogita@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "aparnasn177@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "mananojha475@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "shalinipojha@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "meenu.yadav67@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "mahishrm@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "tiwari.sang@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "binnukumar100@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "shuklaprashant89@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "porwal.saket@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "rekhalohia03@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "sureshlohia1965@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "vedsinghprakash10@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "srinath8321@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "vibhav.ec@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "priti.18jsr@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "jitsingh7989@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "sanjayronp@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "timussharma@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "sharmaajoykumar@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "debasishbhuiya7868@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "sanjusmtr@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "singh.jarnail1291@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "pallavmathut@railtelindia.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "lmb2010@rediffmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "surendraj2eedev@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "ashusafaya@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "anilnagavanshi@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "apss221214@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "adeshtyagi1970@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "93deepak93sharma@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "kopalchaube@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "smartyrathish@yahoo.co.in" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "aratipriya@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "amaninjss@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "shipra.verma2003@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "sdr.jyoti@yahoo.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "sanjuiway@rediffmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "sharmapritika03@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "hariabdesh@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "shi.ogs.m@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "neerajkrshukla@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "swadesh401@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "akansha.singhal04@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "anamikashahi1586@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "mahtourmila65@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "datta.nakade111@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "utkarsh.zen@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "pramod05031980@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "shamsher.kundal39@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "manishagg25@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "adeshvarshney@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "rachnaverm81@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "andyaanu@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "amritpaulap@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "shaileshnri@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "er.deepakvashist@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "vmaurya7@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "nutansaurabh.thakur@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "goel_gaurav@outlook.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "mishra.vivek03@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "navin_mishra@yahoo.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "ismat.ish@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "gautam.samiksha24@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "isha.1010@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "keswanid@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "bajpai.chandra@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "teena.sharma@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "vishal.kanra@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "sharmagaurav1508@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "lavanyashukla09@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "sarlarawat777@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "sks7yu@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "jainshikha250783@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "bhupenderhbti@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "mauryarakesh0903@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "shalupisces1203@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "bansal.lb24@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "ajaysingh369@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "gsdrall@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "rajniduklan98@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "mktyagi1006@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "shubhrasingh1935@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "vbvarunbansal8@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "harendra.bisht2@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "kumar.snl69@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "vandanadevi7@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "anki190494@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "pksinghrcm2002@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "prashant123usin@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "alok.kumar390@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "nidsangel.s@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "mailinavi@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "parul.sagar15@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "suman.singh.rana@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "sun.uday2009@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "meenadeepa076@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "sunainabhatt1991@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "anjaliaidhruvanshi@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "gaurav.kapoor81@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "chaudharyreena078@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "bhawnaomer976@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "amjad233983@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "rinajha1605@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "rush2sonu2001@yahoo.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "kanikaagarwal01@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "vibha.tiwari.1985@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "himanityagi1007@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "ruchikamalhotra0610@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "anuradhasahilrawat09@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "prakashaayush45@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "intouch.manish75@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "rsuppal1952@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "itsviresh@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "manojdhyani87@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "nehaguptaradhe@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "sachinuk20@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "mamtasohini2025@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "utkarsh.yudi30@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "1961hariom@gmil.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "harpuneet.nagi@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "kd70606@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "madhusmitajena.1974@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "reenagaur2001@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "rajputsanju585@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "sinha29637@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "dhanodar83@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "subhash24@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "mamtasohini2026@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "shalinirai387@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "ushakiran4444@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "himanityagi1007@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "manu85bansal@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "bgaur1223@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "swatimusic29@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "hrit_aish1981@rediffmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "susane5380@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "dhiman.pooja@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "geetanjalirajput.1982@ gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "anuradha.rastogi@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "shashivbhushan@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "artivinay5@gmail.com" }, update: { $set: { category: "150" } } } },
        { updateOne: { filter: { "email": "docvarunmalhotra@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "vinaysaini82@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "preetibisht161821@gmail.com" }, update: { $set: { category: "200" } } } },
        { updateOne: { filter: { "email": "nirmaljaingarg@gmail.com" }, update: { $set: { category: "100" } } } },
        { updateOne: { filter: { "email": "maurayakanchan2712@gmail.com" }, update: { $set: { category: "200" } } } },
        // Add more here
    ];

    await Athlete.bulkWrite(bulkOps);
    console.log("✅ Athlete categories updated.");
    mongoose.disconnect();
};

updates().catch(console.error);
