const { withMainActivity } = require('@expo/config-plugins');

module.exports = function withHealthConnectDelegate(config) {
  return withMainActivity(config, async config => {
    let mainActivity = config.modResults.contents;

    const importStatement = 'import dev.matinzd.healthconnect.permissions.HealthConnectPermissionDelegate\n';
    
    // 1. Inject the import if it doesn't exist
    if (!mainActivity.includes('import dev.matinzd.healthconnect.permissions.HealthConnectPermissionDelegate')) {
      mainActivity = mainActivity.replace(
        'class MainActivity : ReactActivity() {',
        `${importStatement}\nclass MainActivity : ReactActivity() {`
      );
    }

    // 2. Inject the delegate initialization right after super.onCreate
    // We look for super.onCreate(...) which is generated by Expo
    const initCode = '\n    HealthConnectPermissionDelegate.setPermissionDelegate(this)\n';
    if (!mainActivity.includes('HealthConnectPermissionDelegate.setPermissionDelegate(this)')) {
        mainActivity = mainActivity.replace(
            /(super\.onCreate\(.*\)\s*)/,
            `$1${initCode}`
        );
    }

    config.modResults.contents = mainActivity;
    return config;
  });
};
